"use client";

import { Transcript, SummaryProvenance } from '@/types';
import { EditableTitle } from '@/components/EditableTitle';
import { labelForCode } from '@/lib/summary-languages';
import { Calendar, Clock, MessageSquare, Cpu, LayoutTemplate, Languages } from 'lucide-react';

interface SummaryMetaHeaderProps {
  title: string;
  isEditingTitle: boolean;
  onStartEditTitle: () => void;
  onFinishEditTitle: () => void;
  onTitleChange: (title: string) => void;
  createdAt: string;
  transcripts: Transcript[];
  /** Null for summaries generated before provenance was stamped. */
  provenance: SummaryProvenance | null;
  availableTemplates: Array<{ id: string; name: string; description: string }>;
}

function formatCreatedAt(createdAt: string): string | null {
  const date = new Date(createdAt);
  if (Number.isNaN(date.getTime())) return null;
  return date.toLocaleString(undefined, {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

/**
 * Meeting length taken from where the last segment ends, which is the recording
 * duration rather than the sum of speech segments (VAD drops the silence).
 */
function meetingDurationSeconds(transcripts: Transcript[]): number | null {
  let end = 0;
  for (const transcript of transcripts) {
    const segmentEnd = transcript.audio_end_time;
    if (typeof segmentEnd === 'number' && Number.isFinite(segmentEnd) && segmentEnd > end) {
      end = segmentEnd;
    }
  }
  return end > 0 ? end : null;
}

function formatDuration(totalSeconds: number): string {
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  if (hours > 0) return `${hours}h ${minutes}m`;
  if (minutes > 0) return `${minutes}m`;
  return `${Math.round(totalSeconds)}s`;
}

/** Turns an unmatched template id such as `daily_standup` into `Daily standup`. */
function prettifyTemplateId(templateId: string): string {
  const words = templateId.replace(/[_-]+/g, ' ').trim();
  if (!words) return templateId;
  return words.charAt(0).toUpperCase() + words.slice(1);
}

function formatProvider(provider: string): string {
  if (!provider) return '';
  return provider.charAt(0).toUpperCase() + provider.slice(1);
}

function MetaItem({
  icon: Icon,
  children,
  title,
}: {
  icon: typeof Calendar;
  children: React.ReactNode;
  title?: string;
}) {
  return (
    <span className="inline-flex items-center gap-1.5 whitespace-nowrap" title={title}>
      <Icon size={13} className="text-gray-400 shrink-0" />
      {children}
    </span>
  );
}

export function SummaryMetaHeader({
  title,
  isEditingTitle,
  onStartEditTitle,
  onFinishEditTitle,
  onTitleChange,
  createdAt,
  transcripts,
  provenance,
  availableTemplates,
}: SummaryMetaHeaderProps) {
  const createdLabel = formatCreatedAt(createdAt);
  const durationSeconds = meetingDurationSeconds(transcripts);
  const segmentCount = transcripts.length;

  // Provenance fields are omitted rather than shown as "unknown": a summary
  // generated before stamping existed has no truthful value to display.
  const templateLabel = provenance
    ? availableTemplates.find((t) => t.id === provenance.template_id)?.name
        ?? prettifyTemplateId(provenance.template_id)
    : null;
  const languageLabel = provenance?.summary_language
    ? labelForCode(provenance.summary_language)
    : null;

  return (
    <div className="mb-3">
      <EditableTitle
        title={title}
        isEditing={isEditingTitle}
        onStartEditing={onStartEditTitle}
        onFinishEditing={onFinishEditTitle}
        onChange={onTitleChange}
      />

      <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 px-1 text-xs text-gray-500">
        {createdLabel && <MetaItem icon={Calendar}>{createdLabel}</MetaItem>}

        {durationSeconds !== null && (
          <MetaItem icon={Clock}>{formatDuration(durationSeconds)}</MetaItem>
        )}

        {segmentCount > 0 && (
          <MetaItem icon={MessageSquare}>
            {segmentCount.toLocaleString()} {segmentCount === 1 ? 'segment' : 'segments'}
          </MetaItem>
        )}

        {provenance && (
          <MetaItem
            icon={Cpu}
            title={`Generated by ${formatProvider(provenance.provider)} / ${provenance.model}`}
          >
            {provenance.model}
          </MetaItem>
        )}

        {templateLabel && <MetaItem icon={LayoutTemplate}>{templateLabel}</MetaItem>}

        {languageLabel && <MetaItem icon={Languages}>{languageLabel}</MetaItem>}
      </div>
    </div>
  );
}
